<?php


/**
 * Implements hook_menu().
 */
function parone_shortcode_menu()
{
    $items = array();

    $items['admin/config/system/parone_shortcode'] = array(
        'title' => 'ParOne Videos',
        'description' => 'Configuration for ParOne shortcodes and available videos.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('parone_shortcode_admin_settings_form'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'parone_shortcode.admin.inc',
    );

    return $items;
}

/** 
 * Implements hook_form_alter(). 
 */
function parone_shortcode_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == "parone_shortcode_admin_settings_form") {
        $form['actions']['submit']['#value'] = t('Save');
        array_push($form['parone_code'], $form['actions']);
        unset($form['actions']);
    }
}

/**
 * Implements hook_preprocess_page().
 */
function parone_shortcode_preprocess_page(&$variables) {
   drupal_add_js("https://sdk.parone.io/parone.min.js", "external");
}

/**
 * Define our shortcodes and their titles, descriptions, and callback functions
 *
 * See comments below for explanation
 */
// function parone_shortcode_shortcode_info() {

//     $shortcodes['parone_video_player'] = array(
//         'title' => t('Parone Video Player'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
//         'description' => t('Outputs parone video block.'),  // Description shown along with the title in the Drupal backend
//         'process callback' => 'parone_shortcode_parone_video_player', // Custom function that deals with the variables and html output
//         'tips callback' => 'parone_shortcode_parone_video_player_tip' // Custom function that displays some help text to the user
//     );

//     return $shortcodes;
// }

// /**
//  * Implements hook_theme().
//  */
// function parone_shortcode_theme() {
//     return array(
//         'shortcode_parone_video_player' => array(
//             'variables' => array(
//                 'campaign' => '', 
//                 'feed' => '', 
//                 'hide-title' => false, 
//                 'hide-logo' => false, 
//                 'hide-description' => false, 
//                 'autoplay' => false
//             ),
//         ),
//     );
// }

// /**
//  * Define our process callback function for our [parone_video_player] shortcode.
//  * 
//  *  $attrs = shortcode_attrs(array(
//  *     'attribute' => 'default_value_goes_here'
//  * ),
//  */
// function parone_shortcode_parone_video_player($attrs) {
//     $processed_attrs = [];
//     foreach($attrs as $key => $value) {
//         if (gettype($key) != "string" && $value != "/" ) {
//             $attr_key_value = explode("=", $value);
//             $processed_attrs[$attr_key_value[0]] = trim($attr_key_value[1], '"');
//         } else {
//             $processed_attrs[$key] = $value;
//         }
//     }

//     return theme('shortcode_parone_video_player', array(
//         'campaign' => $processed_attrs['campaign'] ?? '', 
//         'feed' => $processed_attrs['feed'] ?? '',
//         'hide-title' => $processed_attrs['hide-title'] ?? false, 
//         'hide-logo' => $processed_attrs['hide-logo'] ?? false, 
//         'hide-description' => $processed_attrs['hide-description'] ?? false, 
//         'autoplay' => $processed_attrs['autoplay'] ?? false,
//     ));
// }

// /**
//  * This function uses the attributes passed in to return the HTML of this shortcode.
//  */
// function theme_shortcode_parone_video_player($vars) {
//     $campaign = $vars['campaign'] ?? '';
//     $feed = $vars['feed'] ?? '';
//     $hide_title = $vars['hide-title'] ?? false;
//     $hide_logo = $vars['hide-logo'] ?? false;
//     $hide_description = $vars['hide-description'] ?? false;
//     $autoplay = $vars['autoplay'] ?? false;
//     return "<parone-video-block hide-title=\"{$hide_title}\" hide-logo=\"{$hide_logo}\" hide-description=\"{$hide_description}\" autoplay=\"{$autoplay}\" campaign=\"{$campaign}\" feed=\"{$feed}\"></parone-video-block>";
// }

// /**
//  * This function outputs some tips to the user beneath the WYSIWYG editor so they know
//  * what the shortcode does and how to use it.
//  */
// function parone_shortcode_parone_video_player_tip($format, $long) {
//     $output = array();
//     $output[] = '<p><strong>' . t('[parone_video_player campaign="Campaign ID" feed="Feed ID"/] outputs a base ParOne video block') . '</strong> ';
  
//     return implode(' ', $output);
// }